#Templates :
AssetFileName : "{AssetFileName}.{Ext}"
Project : "C:/Users/Natspir/NatspirProd/03_WORK_PIPE/01_ASSET_3D"
AssetPath : "{AssetType}\\{AssetName}"
FileDir : "$AssetPath\\{Task}\\{Subtask}\\{Version}"
File : "$FileDir\\$AssetFileName"
Workspace : "$File"
Render : "$Workspace/Render"
Cache : "$Workspace/Cache"
Textures : "$Workspace/Textures"
Flip : "$Workspace/flip"
